//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.18 at 11:45:42 AM GMT 
//


package psidev.psi.mi.jami.bridges.uniprot.rest.response.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accession" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dbReference" type="{http://uniprot.org/uniparc}dbReferenceType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="signatureSequenceMatch" type="{http://uniprot.org/uniparc}seqFeatureType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://uniprot.org/uniparc}sequence"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="dataset" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="UniProtKB_exclusion" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accession",
    "dbReference",
    "signatureSequenceMatch",
    "sequence"
})
@XmlRootElement(name = "entry")
public class Entry {

    @XmlElement(required = true)
    protected String accession;
    @XmlElement(required = true)
    protected List<DbReferenceType> dbReference;
    protected List<SeqFeatureType> signatureSequenceMatch;
    @XmlElement(required = true)
    protected Sequence sequence;
    @XmlAttribute(name = "dataset", required = true)
    protected String dataset;
    @XmlAttribute(name = "UniProtKB_exclusion")
    protected String uniProtKBExclusion;

    /**
     * Gets the value of the accession property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAccession() {
        return accession;
    }

    /**
     * Sets the value of the accession property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAccession(String value) {
        this.accession = value;
    }

    /**
     * Gets the value of the dbReference property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dbReference property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDbReference().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DbReferenceType }
     *
     *
     */
    public List<DbReferenceType> getDbReference() {
        if (dbReference == null) {
            dbReference = new ArrayList<DbReferenceType>();
        }
        return this.dbReference;
    }

    /**
     * Gets the value of the signatureSequenceMatch property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signatureSequenceMatch property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignatureSequenceMatch().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SeqFeatureType }
     *
     *
     */
    public List<SeqFeatureType> getSignatureSequenceMatch() {
        if (signatureSequenceMatch == null) {
            signatureSequenceMatch = new ArrayList<SeqFeatureType>();
        }
        return this.signatureSequenceMatch;
    }

    /**
     * Gets the value of the sequence property.
     *
     * @return
     *     possible object is
     *     {@link Sequence }
     *
     */
    public Sequence getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     *
     * @param value
     *     allowed object is
     *     {@link Sequence }
     *     
     */
    public void setSequence(Sequence value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the dataset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataset() {
        return dataset;
    }

    /**
     * Sets the value of the dataset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataset(String value) {
        this.dataset = value;
    }

    /**
     * Gets the value of the uniProtKBExclusion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniProtKBExclusion() {
        return uniProtKBExclusion;
    }

    /**
     * Sets the value of the uniProtKBExclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniProtKBExclusion(String value) {
        this.uniProtKBExclusion = value;
    }

}
