//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.13 at 08:35:31 AM GMT 
//


package psidev.psi.mi.jami.bridges.uniprot.rest.response.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.ebi.intact.bridges.uniprot.rest.uniparc.response.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.ebi.intact.bridges.uniprot.rest.uniparc.response.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Uniparc }
     * 
     */
    public Uniparc createUniparc() {
        return new Uniparc();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link DbReferenceType }
     * 
     */
    public DbReferenceType createDbReferenceType() {
        return new DbReferenceType();
    }

    /**
     * Create an instance of {@link SeqFeatureType }
     * 
     */
    public SeqFeatureType createSeqFeatureType() {
        return new SeqFeatureType();
    }

    /**
     * Create an instance of {@link Sequence }
     * 
     */
    public Sequence createSequence() {
        return new Sequence();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link SeqFeatureGroupType }
     * 
     */
    public SeqFeatureGroupType createSeqFeatureGroupType() {
        return new SeqFeatureGroupType();
    }

}
