//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.18 at 11:45:42 AM GMT 
//


package psidev.psi.mi.jami.bridges.uniprot.rest.response.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the psidev.psi.mi.jami.bridges.uniprot.rest.response.model.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: psidev.psi.mi.jami.bridges.uniprot.rest.response.model.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.Uniparc}
     *
     * @return a {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.Uniparc} object.
     */
    public Uniparc createUniparc() {
        return new Uniparc();
    }

    /**
     * Create an instance of {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.Entry}
     *
     * @return a {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.Entry} object.
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.DbReferenceType}
     *
     * @return a {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.DbReferenceType} object.
     */
    public DbReferenceType createDbReferenceType() {
        return new DbReferenceType();
    }

    /**
     * Create an instance of {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.SeqFeatureType}
     *
     * @return a {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.SeqFeatureType} object.
     */
    public SeqFeatureType createSeqFeatureType() {
        return new SeqFeatureType();
    }

    /**
     * Create an instance of {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.Sequence}
     *
     * @return a {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.Sequence} object.
     */
    public Sequence createSequence() {
        return new Sequence();
    }

    /**
     * Create an instance of {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.PropertyType}
     *
     * @return a {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.PropertyType} object.
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.LocationType}
     *
     * @return a {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.LocationType} object.
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.SeqFeatureGroupType}
     *
     * @return a {@link psidev.psi.mi.jami.bridges.uniprot.rest.response.model.SeqFeatureGroupType} object.
     */
    public SeqFeatureGroupType createSeqFeatureGroupType() {
        return new SeqFeatureGroupType();
    }

}
