//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.18 at 11:45:42 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uniprot.org/uniparc", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package psidev.psi.mi.jami.bridges.uniprot.rest.response.model;
