//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.13 at 08:35:31 AM GMT 
//


package psidev.psi.mi.jami.bridges.uniprot.rest.response.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for seqFeatureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="seqFeatureType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ipr" type="{http://uniprot.org/uniparc}seqFeatureGroupType" minOccurs="0"/&gt;
 *         &lt;element name="lcn" type="{http://uniprot.org/uniparc}locationType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="database" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "seqFeatureType", propOrder = {
    "ipr",
    "lcn"
})
public class SeqFeatureType {

    protected SeqFeatureGroupType ipr;
    @XmlElement(required = true)
    protected List<LocationType> lcn;
    @XmlAttribute(name = "database", required = true)
    protected String database;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the ipr property.
     * 
     * @return
     *     possible object is
     *     {@link SeqFeatureGroupType }
     *     
     */
    public SeqFeatureGroupType getIpr() {
        return ipr;
    }

    /**
     * Sets the value of the ipr property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqFeatureGroupType }
     *     
     */
    public void setIpr(SeqFeatureGroupType value) {
        this.ipr = value;
    }

    /**
     * Gets the value of the lcn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lcn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLcn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationType }
     * 
     * 
     */
    public List<LocationType> getLcn() {
        if (lcn == null) {
            lcn = new ArrayList<LocationType>();
        }
        return this.lcn;
    }

    /**
     * Gets the value of the database property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabase() {
        return database;
    }

    /**
     * Sets the value of the database property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabase(String value) {
        this.database = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
